//TODO: add an area to see what players are connected, create a way to load all saved maps and switch between them.  Perhaps add a drop down box to switch to a specific map?

package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.MouseListener;

/*
 * Lobby.java
 *
 * Created on Dec 4, 2011, 3:29:03 PM
 */
/**
 *
 * @author Sean
 */
@SuppressWarnings("serial")
public class TanksLobby extends MasterPanel {

    /** Creates new form Lobby */
    public TanksLobby(TanksFrame t) {
    	super(t);
        initComponents();
        listeners();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
	protected void initComponents() {

    	 //DON'T MESS WITH THIS.  This sets up all the manual placements and stuff.
    	
    	previous = new javax.swing.JButton();
        next = new javax.swing.JButton();
        mainMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        weaponList = new javax.swing.JList();
        mapDropDownSelector = new javax.swing.JComboBox();
        mapPreview = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        weaponInfo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tankList = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        tankInfo = new javax.swing.JTextArea();
        playButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        previous.setText("Previous");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        next.setText("Next");

        mainMenu.setText("Main Menu");

        weaponList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Normal cannon", "Plasma cannon" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(weaponList);

        mapDropDownSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        mapPreview.setFocusable(false);

        javax.swing.GroupLayout mapPreviewLayout = new javax.swing.GroupLayout(mapPreview);
        mapPreview.setLayout(mapPreviewLayout);
        mapPreviewLayout.setHorizontalGroup(
            mapPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mapPreviewLayout.setVerticalGroup(
            mapPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        weaponInfo.setColumns(20);
        weaponInfo.setRows(5);
        jScrollPane2.setViewportView(weaponInfo);

        tankList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Small Tank", "Medium Tank", "Large Tank" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(tankList);

        tankInfo.setColumns(20);
        tankInfo.setRows(5);
        jScrollPane4.setViewportView(tankInfo);

        playButton.setText("Play!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previous)
                        .addGap(177, 177, 177)
                        .addComponent(mapPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainMenu)
                                .addGap(62, 62, 62)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(next)
                    .addComponent(playButton))
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(mapDropDownSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(next))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(previous)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(mapPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(mapDropDownSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainMenu)
                                .addGap(30, 30, 30))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playButton)
                        .addGap(30, 30, 30))))
        );
      //OKAY DO WHAT YOU WANT TO NOW.
        
        
        
      //Manually added code, not part of Netbeans
       
        //End of manually added code not from NetBeans
    }
    
    protected void listeners()
    {
    	 mainMenu.addActionListener(new mainMenuListener());
         
         tankList.addMouseListener(new tankSelectionListener());         
    }
        
    
    

private void previousActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

// Variables declaration - do not modify
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JButton mainMenu;
	private javax.swing.JComboBox mapDropDownSelector;
	private javax.swing.JPanel mapPreview;
	private javax.swing.JButton next;
	protected javax.swing.JButton playButton;
	private javax.swing.JButton previous;
	private javax.swing.JTextArea tankInfo;
	private javax.swing.JList tankList;
	private javax.swing.JTextArea weaponInfo;
	private javax.swing.JList weaponList;
// End of variables declaration
   
    
    private class mainMenuListener implements ActionListener
    {
    	public void actionPerformed(ActionEvent arg0)
    	{
    		t.changeViews(Views.MAIN);
    	}
    }
    
    private class tankSelectionListener implements MouseListener

    {
    	
		@Override
		public void mouseClicked(MouseEvent arg0) {
			int tempSelection = tankList.getSelectedIndex();
    		
    		switch(tempSelection)
    		{
    		case (0):
    			GUI_Info_SmallTank tempSmallTank = new GUI_Info_SmallTank();
    			tankInfo.setText(tempSmallTank.getInfo());
    			break;
    		case (1):
    			tankInfo.setText("MEDIUM TANK");
    			break;
    		default:
    			//do nothing
    		}
		}

		@Override
		public void mouseEntered(MouseEvent arg0) {
			//Do Nothing
			
		}

		@Override
		public void mouseExited(MouseEvent arg0) {
			//Do Nothing
			
		}

		@Override
		public void mousePressed(MouseEvent arg0) {
			//Do Nothing
			
		}

		@Override
		public void mouseReleased(MouseEvent arg0) {
			//Do Nothing
			
		}
    }

    
}


